Rename env.py to environment.py
Geson-anko/PynkTromboneGym pull request #153
Opened 2024-03-05 05:09 UTC by sandeepnmenon

For issue #74

2024-03-06 05:56 UTC, Geson-anko requested changes
@sandeepnmenon Thank you very much, but there are some requests.

1. Please rename `test_env.py` to `test_environment.py`: To keep consistency with `environment.py`. (The test file naming rule is `test_<target_file_name>.py`
2. Please change pull request target to `dev` because this pr is a destructive change. I have to check my project that uses this repo. After the check, I'll merge to master branch.

2024-03-06 07:14 UTC, sandeepnmenon commented
@Geson-anko 
1. Renamed `test_env.py` to `test_environment.py`
2. Changed target branch to `dev`

2024-03-07 01:54 UTC, Geson-anko approved these changes

2024-03-07 01:55 UTC, Geson-anko commented
@sandeepnmenon Thank you very much !!!

2024-03-07 01:55 UTC, merged